[package]
name = "shortest-color"
version = "0.1.4"
edition = "2021"
description = "Color shortener"
license = "MIT"
repository = "https://github.com/rostislavnagimov/shortest-color"
keywords = ["color", "css", "hex", "web", "optimization"]
categories = ["web-programming", "parsing", "graphics"]

include = ["src/lib.rs"]

[lib]
crate-type = ["cdylib", "rlib"]

[[bench]]
name = "p"
path = "benches/performance.rs"
harness = false

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false