[package]
name = "shortest-color"
version = "0.1.2"
edition = "2021"
description = "Fastest color shortener"
license = "MIT"
repository = "https://github.com/rostislavnagimov/shortest-color"
keywords = ["parser", "web", "parsing", "css", "utility"]
categories = ["web-programming", "development-tools", "parsing"]

include = ["src/lib.rs"]

[lib]
crate-type = ["cdylib", "rlib"]

[[bench]]
name = "p"
path = "benches/performance.rs"
harness = false

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false